# REFERENCE: https://github.com/isa-asistent/Vezbe-2025/tree/main/vezbe4/spring-security-example
server.port=8080

spring.application.name=Jutjubic - back-end

# REFERENCE: https://www.javacodegeeks.com/rest-api-security-with-spring-security-jwt-token-signing.html
secret-of-application=post-express-irvas-univerexport-2025-2026-b92-net-slash-sport-basketball-realgm-com-patike-cipele-gradska-linija-9-bb-elektronik
life-duration-of-token-in-milliseconds=3600000
name-of-auth-header=Authorization

# REFERENCE: https://github.com/isa-asistent/Vezbe-2025/tree/main/vezbe3/jpa_example
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.platform=postgresql
# REFERENCE: https://www.pgadmin.org/docs/pgadmin4/4.14/schema_dialog.html
spring.datasource.url=jdbc:postgresql://localhost:5432/jutjubic
spring.datasource.username=postgres
spring.datasource.password=password

# REFERENCE: https://docs.spring.io/spring-boot/docs/2.7.0/reference/html/howto.html#howto.data-initialization
spring.jpa.defer-datasource-initialization=true
spring.jpa.generate-ddl=true
# REFERENCE: https://vladmihalcea.com/the-open-session-in-view-anti-pattern/
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
# REFERENCE: https://www.baeldung.com/spring-boot-data-sql-and-schema-sql
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
# REFERENCE: https://stackoverflow.com/questions/43905119/postgres-error-method-org-postgresql-jdbc-pgconnection-createclob-is-not-imple
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# REFERENCE: https://docs.spring.io/spring-boot/docs/2.7.0/reference/html/howto.html#howto.data-initialization
spring.sql.init.mode=always
spring.sql.init.platform=postgresql
