# REFERENCE: https://github.com/isa-asistent/Vezbe-2025/tree/main/vezbe4/spring-security-example
server.port=8080

spring.application.name=Jutjubic - back-end

# REFERENCE: https://www.javacodegeeks.com/rest-api-security-with-spring-security-jwt-token-signing.html
secret-of-application=post-express-irvas-univerexport-2025-2026-b92-net-slash-sport-basketball-realgm-com-patike-cipele-gradska-linija-9-bb-elektronik
life-duration-of-token-in-milliseconds=3600000
name-of-auth-header=Authorization

# REFERENCE: https://github.com/isa-asistent/Vezbe-2025/tree/main/vezbe3/jpa_example
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.platform=postgresql
# REFERENCE: https://www.pgadmin.org/docs/pgadmin4/4.14/schema_dialog.html
spring.datasource.url=jdbc:postgresql://localhost:5432/jutjubic
spring.datasource.username=postgres
spring.datasource.password=password

# REFERENCE: https://docs.spring.io/spring-boot/docs/2.7.0/reference/html/howto.html#howto.data-initialization
spring.jpa.defer-datasource-initialization=true
spring.jpa.generate-ddl=true
# REFERENCE: https://vladmihalcea.com/the-open-session-in-view-anti-pattern/
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
# REFERENCE: https://www.baeldung.com/spring-boot-data-sql-and-schema-sql
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
# REFERENCE: https://stackoverflow.com/questions/43905119/postgres-error-method-org-postgresql-jdbc-pgconnection-createclob-is-not-imple
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# REFERENCE: https://github.com/isa-asistent/Vezbe-2025/tree/main/vezbe2/async_example
# REFERENCE: https://mailtrap.io/blog/spring-send-email/
spring.mail.host=smtp.gmail.com
# REFERENCE: https://support.google.com/accounts/answer/185833
spring.mail.password=yhsnrktbgjrivpom
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
# REFERENCE: https://stackoverflow.com/questions/16115453/javamail-could-not-convert-socket-to-tls-gmail
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.username=isa.tim30.darijan.micic.2022.2023

# REFERENCE: https://medium.com/@vivekrajyaguru1993/how-i-built-a-simple-rate-limiter-in-spring-boot-using-redis-step-by-step-3b70d6dee066
# REFERENCE: https://oneuptime.com/blog/post/2026-03-31-redis-what-does-noauth-authentication-required-mean-in-redis/view
spring.redis.host=localhost
spring.redis.password=Doba28_hra^0st
spring.redis.port=6379
spring.redis.username=default

# REFERENCE: https://docs.spring.io/spring-boot/docs/2.7.0/reference/html/howto.html#howto.data-initialization
spring.sql.init.mode=always
spring.sql.init.platform=postgresql
