spring.application.name=Jutjubic - back-end

secret-of-application=post-express-irvas-univerexport-2025-2026-b92-net-slash-sport-basketball-realgm-com-patike-cipele-gradska-linija-9-bb-elektronik
life-duration-of-token-in-milliseconds=3600000
name-of-auth-header=Authorization
